-- REVENUE PER PRODUCT CATEGORY BY EMPLOYEE (YEAR 2014)
-- This query calculates the total revenue generated by each employee for every product category during the year 2014.
-- Revenue is computed as (quantity × unit price) for each order item.
-- CASE expressions are used to separate revenue by product category.
-- Results are grouped by employee to show category-level sales performance per employee.

SELECT 
	e.employeeName,
    SUM(CASE WHEN categoryName = 'Beverages' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueBeverages,
    SUM(CASE WHEN categoryName = 'Condiments' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueCondiments,
    SUM(CASE WHEN categoryName = 'Confections' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueConfections,
    SUM(CASE WHEN categoryName = 'Dairy Products' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueDairy_Products,
    SUM(CASE WHEN categoryName = 'Grains & Cereals' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueGrainsAndCereals,
    SUM(CASE WHEN categoryName = 'Meat & Poultry' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueMeatAndPoultry,
    SUM(CASE WHEN categoryName = 'Produce' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueProduce,
    SUM(CASE WHEN categoryName = 'Seafood' THEN (od.quantity * od.unitPrice) ELSE 0 END) AS TotarRevenueSeafood
FROM
	order_details od 
LEFT JOIN orders o ON od.orderID = o.orderID
LEFT JOIN employees e ON o.employeeID = e.employeeID
LEFT JOIN products p ON od.productID = p.productID
LEFT JOIN categories c ON p.categoryID = c.categoryID 
WHERE
	YEAR(o.orderDate) = 2014
GROUP BY 
	e.employeeName;